# Generated by Django 4.1.7 on 2023-07-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uap", "0003_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uap.category",
            ),
        ),
    ]
